# Generated by Django 6.0.2 on 2026-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='concept',
            name='difficulty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
